### All-Time Analyses

In [1]:
%run prepare.ipynb

### Top Artists

In [2]:
top_artists = streams.pivot_table(
    index='artist',
    values=['ms_played', 'uri', 'track', 'date'],
    aggfunc={'ms_played':'sum', 'uri': 'count', 'track': 'nunique', 'date': 'nunique'},
).sort_values(by='ms_played',ascending=False).head(10)
top_artists['h'] = round(top_artists['ms_played'] / MS2H)
top_artists

                    date   ms_played  track   uri      h
artist
Taylor Swift        1036  1599595121    328  7887  444.3
Tyler, The Creator  1128   963362412    124  5416  267.6
Lorde                780   620991146     63  3317  172.5
Phoebe Bridgers      467   272797770     41  1338   75.8
Lana Del Rey         494   267572379    128  1243   74.3
Ariana Grande        403   260757966     85  1552   72.4
Olivia Rodrigo       486   241437855     31  1366   67.1
boygenius            278   196747990     23  1011   54.7
Doja Cat             410   182487398     43  1105   50.7
Lucy Dacus           259   164685971     51   754   45.7

### Top Tracks

In [4]:
top_tracks = streams.pivot_table(
    index='track',
    values=['ms_played', 'uri', 'date'],
    aggfunc={'ms_played':'sum', 'uri': 'count', 'date': 'nunique'},
).sort_values(by='ms_played',ascending=False).head(10)
top_tracks['h'] = round(top_tracks['ms_played'] / MS2H, 1)
top_tracks

                                                    date  ms_played  uri     h
track
GONE, GONE / THANK YOU                               213   96169036  319  26.7
After The Storm (feat. Tyler, The Creator & Boo...   205   49301912  266  13.7
EARFQUAKE                                            188   45605042  269  12.7
I Know The End                                        86   44401270  139  12.3
Nettles                                               43   43519030  112  12.1
A BOY IS A GUN*                                      170   41788459  239  11.6
SWEET / I THOUGHT YOU WANTED TO DANCE (feat. Br...    89   40767060  117  11.3
All Too Well (10 Minute Version) (Taylor's Vers...    69   38139338   82  10.6
Best Friend                                           86   36658023  162  10.2
GRoCERIES                                            116   35181110  189   9.8

### Top Albums

In [5]:
top_albums = streams.pivot_table(
    index='album',
    values=['ms_played', 'uri', 'date'],
    aggfunc={'ms_played':'sum', 'uri': 'count', 'date': 'nunique'},
).sort_values(by='ms_played',ascending=False).head(10)
top_albums['h'] = round(top_albums['ms_played'] / MS2H, 1)
top_albums

                             date  ms_played   uri     h
album
IGOR                          502  327014165  1669  90.8
Speak Now                     357  243720961  1057  67.7
Red (Taylor's Version)        354  231306253  1035  64.3
Fearless (Taylor's Version)   433  220900636  1116  61.4
Solar Power                   376  206996134  1126  57.5
Flower Boy                    424  193644113  1158  53.8
Punisher                      343  189195493   908  52.6
Melodrama                     392  182902497   936  50.8
the record                    243  146018303   718  40.6
Midnights                     210  138301823   790  38.4

### Streaming Countries

In [3]:
countries = streams.pivot_table(
    index='conn_country',
    values=['ms_played', 'uri', 'track'],
    aggfunc={'ms_played':'sum', 'uri': 'count'},
).sort_values(by='ms_played',ascending=False)
countries['h'] = countries['ms_played'] / MS2H
countries

                ms_played    uri            h
conn_country
CA            11103373205  63201  3084.270335
FR               25350839    103     7.041900
IT               19205416    109     5.334838
GB               17025656     84     4.729349
PT               14457464     70     4.015962
US               11504048     57     3.195569
ES               10392990     56     2.886942
ZZ                3294302     22     0.915084

### All-Time Streaming Metrics

In [5]:
total_ms = df["ms_played"].sum()

[('ms', total_ms), ('h', total_ms / MS2H),
streams.agg({"ms_played": "sum", "uri": "count", "artist": "nunique", "track": "nunique"})]

[('ms', 11454297633),
 ('h', 3181.7493425),
 ms_played    11204603920
 uri                63702
 artist              1556
 track               5416
 dtype: int64]

### Cumulative Top Artists Throughout Years

In [7]:
top_artists = streams.loc['2018':'2021'].pivot_table(
    index='artist',
    values=['ms_played', 'uri', 'track', 'date'],
    aggfunc={'ms_played':'sum', 'uri': 'count', 'track': 'nunique', 'date': 'nunique'},
).sort_values(by='ms_played',ascending=False).head(10)
top_artists['h'] = round(top_artists['ms_played'] / MS2H)
top_artists

                    date  ms_played  track   uri      h
artist
Tyler, The Creator   552  448583254     65  2494  125.0
Lorde                202  143524972     45   788   40.0
Taylor Swift         127  137852043    130   708   38.0
Travis Scott         137  120288173     24   671   33.0
Rex Orange County    234  109272613     18   525   30.0
Doja Cat             153   95595700     34   570   27.0
Kanye West           155   93285855     22   516   26.0
COTIS                166   92112683     19   566   26.0
Ariana Grande         85   91091328     22   520   25.0
BROCKHAMPTON         199   83128681     18   425   23.0