In [2]:
import pandas as pd
import numpy as np
import json
import matplotlib.pyplot as plt
import matplotlib as mpl
# from copy import copy
# from matplotlib.colors import PowerNorm
import squarify
import plotly.express as px
from plotly.offline import init_notebook_mode, iplot
init_notebook_mode(connected=True)  
# import plotly.io as pio
# pio.renderers.default = 'iframe_connected'

In [22]:
top_albums = pd.read_csv("./csv/top_albums.csv")


genres = {}
with open('csv/genres.json', 'r') as f:
  genres = json.load(f)

scores = {}
for i, row in top_albums.iterrows():
  album, ms_played = row[0], row[3]
  grs = genres[album]
  for g in grs:
    if g in scores:
      scores[g] += ms_played
    else:
      scores[g] = ms_played
      
scores = pd.DataFrame.from_dict(scores, orient='index', columns=['ms_played'])
scores.sort_values(by="ms_played", ascending=False)
scores = scores.head(50) / 1000 / 60 / 60


def get_color(genre):
  macrogenres = {
    'rock': '1',
    'folk': "2", 'indie': "2", 'americana': '2', 'alternative': "2",
    'r&b': "3", 'soul': "3",
    'pop': '4'
  }
  for g in macrogenres.keys():
    if g in genre: return macrogenres[g]
  # print(genre)
  return '#385'

fig = px.treemap(
    names = scores.index,
    parents = [""] * len(scores.index),
    values= scores["ms_played"],
    color = list(map(get_color, scores.index)),
    color_discrete_map={"(?)": "385", "1": "#500", "2": "#fb0", "3": "#ff8", "4": "#99e"}
)
fig.update_layout(margin = dict(t=0, l=0, r=0, b=0))
fig.show()

In [51]:
top_albums = pd.read_csv("./csv/top_albums.csv", index_col=0)
top_albums.reset_index().head(10)

,album,artist,date,ms_played,uri,h
0,eternal sunshine,Ariana Grande,116,79835852,475,22.2
1,Virgin,Lorde,41,50745864,307,14.1
2,"Willoughby Tucker, I'll Always Love You",Ethel Cain,48,47345582,121,13.2
3,Calico,Ryan Beatty,35,30640914,153,8.5
4,Kansas Anymore,ROLE MODEL,95,27897845,146,7.7
5,CHROMAKOPIA,"Tyler, The Creator",48,25338168,130,7.0
6,Addison,Addison Rae,68,24436902,156,6.8
7,Backflips in a Restaurant,grentperez,40,23122957,137,6.4
8,Charm,Clairo,68,22913168,126,6.4
9,Forever Is A Feeling,Lucy Dacus,61,22224294,133,6.2

In [67]:
dated_streams = pd.read_csv("./csv/dated_streams.csv", index_col=0)
track_counts = dated_streams[dated_streams['reason_end'] == 'trackdone'].pivot_table(
  index=['track', 'artist'],
  values=['uri'],
  aggfunc={'uri': 'count'}
)

track_counts = track_counts[track_counts["uri"] >= 3].reset_index()

singles = track_counts['artist'].value_counts()
singles = singles[singles == 1]

track_counts = track_counts[track_counts['artist'].isin(singles.index)]
track_counts[track_counts['uri'] > 10]

                                                 track         artist  uri
21                         At The Beach, In Every Life     Gigi Perez   12
95                          Everyday Is A Winding Road    Sheryl Crow   29
106                    Flightless Bird, American Mouth    Iron & Wine   22
193                                   My Favorite Part     Mac Miller   20
215                                Pencil Full of Lead   Paolo Nutini   14
222  Please, Please, Please, Let Me Get What I Want...     The Smiths   17
259                                         Sports car     Tate McRae   16
321                                          Wonderful  Jeff Goldblum   15
341                                    drive ME crazy!     Lil Yachty   16
376                                       ur so pretty  Wasia Project   11

In [55]:
dated_streams[dated_streams['track'] == 'Bluest Flame']

,ms_played,reason_start,reason_end,track,artist,album,uri,conn_country,date
ts,,,,,,,,,
2025-04-04 07:15:00-07:00,162995,trackdone,trackdone,Bluest Flame,Selena Gomez,I Said I Love You First,spotify:track:6vuVCtwukUA57ioTnKKeuL,CA,2025-04-04
2025-04-04 15:57:29-07:00,91382,trackdone,logout,Bluest Flame,Selena Gomez,I Said I Love You First,spotify:track:6vuVCtwukUA57ioTnKKeuL,CA,2025-04-04
2025-04-05 09:54:56-07:00,71730,appload,trackdone,Bluest Flame,Selena Gomez,I Said I Love You First,spotify:track:6vuVCtwukUA57ioTnKKeuL,CA,2025-04-05
2025-04-09 16:20:44-07:00,75960,trackdone,fwdbtn,Bluest Flame,Selena Gomez,I Said I Love You First,spotify:track:6vuVCtwukUA57ioTnKKeuL,CA,2025-04-09
2025-04-10 07:16:33-07:00,34280,trackdone,fwdbtn,Bluest Flame,Selena Gomez,I Said I Love You First,spotify:track:6vuVCtwukUA57ioTnKKeuL,CA,2025-04-10
2025-04-21 15:51:25-07:00,98653,trackdone,fwdbtn,Bluest Flame,Selena Gomez,I Said I Love You First,spotify:track:6vuVCtwukUA57ioTnKKeuL,CA,2025-04-21
2025-04-25 15:11:04-07:00,85366,trackdone,fwdbtn,Bluest Flame,Selena Gomez,I Said I Love You First,spotify:track:6vuVCtwukUA57ioTnKKeuL,CA,2025-04-25
2025-05-20 17:35:32-07:00,52867,trackdone,logout,Bluest Flame,Selena Gomez,I Said I Love You First,spotify:track:6vuVCtwukUA57ioTnKKeuL,CA,2025-05-20
2025-06-20 19:40:09-07:00,33865,trackdone,fwdbtn,Bluest Flame,Selena Gomez,I Said I Love You First,spotify:track:6vuVCtwukUA57ioTnKKeuL,CA,2025-06-20
2025-07-25 19:56:23-07:00,31959,trackdone,fwdbtn,Bluest Flame,Selena Gomez,I Said I Love You First,spotify:track:6vuVCtwukUA57ioTnKKeuL,CA,2025-07-25