In [54]:
import pandas as pd
import numpy as np
import json
import matplotlib.pyplot as plt
import matplotlib as mpl
from copy import copy
from matplotlib.colors import PowerNorm

In [4]:
top_tracks = pd.read_csv("./csv/top_tracks.csv", index_col=0)
top_tracks.head(10).reset_index()

                   track  date  ms_played  uri     h
0                Nettles    42   43035338  111  12.0
1              Hampstead    39   11380568   53   3.2
2         Some Protector    41   11296063   53   3.1
3             Best Guess    38   10452604   48   2.9
4          What Was That    39   10362873   61   2.9
5          twilight zone    40   10165859   58   2.8
6              dandelion    39    9753788   55   2.7
7                 Greedy    38    9554228   48   2.7
8  Angels All Around Me…    29    8799354   37   2.4
9          Headphones On    36    8669441   43   2.4

In [7]:
ms = pd.date_range(start="2025-01", end="2025-12", freq='MS')
mtt = pd.read_csv("./csv/monthly_top_tracks.csv", index_col=0)
mtt = mtt[[col for col in mtt if col.startswith('2025')]].head(5)

mtt

,2025-01,2025-02,2025-03,2025-04,2025-05,2025-06,2025-07,2025-08,2025-09,2025-10,2025-11,2025-12
1,i wish i hated you,Greedy,Best Guess,twilight zone,Sue me,Nettles,Nettles,The Subway,Cinnamon Bread,The Fate of Ophelia,Wonderful,March of the Witch Hunters
2,true story,"Sticky (feat. GloRilla, Sexyy Red & Lil Wayne)",Dandelion,Fuzzy Feeling,Angels All Around Me…,Everyday Is A Winding Road,Man Of The Year,American Teenager,Hunter,Elizabeth Taylor,No Good Deed,Wonderful
3,eternal sunshine,Nomad,past life,dandelion,dandelion,Time To Say Goodbye,What Was That,Big Deal,Bruises Off The Peach,The Life of a Showgirl (feat. Sabrina Carpenter),Sun Bleached Flies,No Good Deed
4,bye,Busy Woman,dandelion,"Sally, When The Wine Runs Out",What Was That,Man Of The Year,Shapeshifter,Some Protector,Multiple Endings,Opalite,Bruises Off The Peach - Live Performance,Every Day More Wicked
5,supernatural,intro (end of the world),drive ME crazy!,Sunshine & Rain...,twilight zone,Money is Everything,Favourite Daughter,Somebody Else - Spotify Singles,Andromeda,Actually Romantic,"Big Guy - from ""The SpongeBob Movie: Search fo...",As Long As You’re Mine

In [69]:
# TODO: move the code for this and streaks to here (its)
sds = pd.read_csv("./csv/single_day_streams.csv", index_col=0)
sds[['track', 'uri', 'date']]

                        track  uri        date
597               Cherry Wine    7  2025-04-14
766                     David    5  2025-06-29
1290                   Greedy    5  2025-02-12
1622  If She Could See Me Now    6  2025-06-29
1909          Man Of The Year    9  2025-05-29
2140                  Nettles    5  2025-06-16
2145                  Nettles    6  2025-06-23
2148                  Nettles    6  2025-06-26
2979       Sun Bleached Flies    5  2025-11-04

In [68]:
strks = pd.read_csv("./csv/streaks.csv", index_col=0)
strks['end'] = pd.to_datetime(strks['date'])
strks['start'] = strks['end'] - pd.to_timedelta(strks['streak'] - 1, unit='d') #+ pd.Timedelta(days=1)
strks[['track', 'streak', 'start', 'end']]

                   track  streak      start        end
3733      Some Protector       7 2025-05-24 2025-05-30
2870             Nettles       7 2025-06-20 2025-06-26
867            Clearblue       6 2025-07-12 2025-07-17
967      Current Affairs       6 2025-07-12 2025-07-17
3732      Some Protector       6 2025-05-24 2025-05-29
1408  Favourite Daughter       6 2025-06-27 2025-07-02
2869             Nettles       6 2025-06-20 2025-06-25
2593     Man Of The Year       6 2025-06-26 2025-07-01
1415  Favourite Daughter       6 2025-07-12 2025-07-17
2601     Man Of The Year       6 2025-07-12 2025-07-17